service: view-spot-finder

frameworkVersion: '2 || 3'

plugins:
  - serverless-plugin-typescript

provider:
  name: aws
  runtime: nodejs12.x
  lambdaHashingVersion: 20201221

functions:
  getMesh:
    handler: src/index.getMesh
